on:
  push:
    branches:
      - Developer

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug repository contents
        run: ls -la

      - name: Change to project directory
        run: cd WebPortfolio

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0
          cache: 'npm'
          cache-dependency-path: WebPortfolio/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: WebPortfolio

      - name: Build project
        run: npm run build
        working-directory: WebPortfolio

      - name: Verify build output
        run: ls -la WebPortfolio/dist

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: WebPortfolio/dist
